FROM resin/raspberrypi-python:2.7

#switch on systemd init system in container
ENV INITSYSTEM on


# PiFace
RUN apt-get install python-pifacedigitalio


# pip install python deps from requirements.txt
# For caching until requirements.txt changes
COPY ./requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

COPY . /usr/src/app
WORKDIR /usr/src/app

CMD ["python3", "/usr/share/doc/python-pifacedigitalio/examples/blink.py"]